### ISSUE TITLE
Judgement #1

### ISSUE THREAD

**Issue by GeneTv** [janisringli/dashboard#1]
Ever heard of a folder like `web/` or something like that?

**Comment by janisringli** [comment]
> Ever heard of a folder like `web/` or something like that?

Good evening mr GeneTv
Thanks for your feedback. I will take that into consideration although I can't really see the usecase of such a folder because its only a static message. In the future, when I begin with the development of my portfolio, a better repository structure will be mandatory. But for now when there is obly plain text on it, i will decline your said "judgment" and continue to live in peace. 
Most sincerely
Janis

**Comment by GeneTv** [comment]
Good evening Sir Vandenhiven

Thanks for you decline. Unfortunately, I must inform you that "live in peace" won't work with the path you chose with this.

 Most sincerely,
 GeneTv
